// The look-and-say sequence is defined as follows:

// Its first term is equal to 1.
// The nth term (for n > 1) is generated by reading the (n-1)th term.
// Thus,

// the second term is 11, generated by reading the first term as "One 1" (There is one 1 in previous term);
// the third term is 21, generated by reading the second term as "Two 1";
// the fourth term is 1211, generated by reading the third term as "One 2 One 1";
// and so on.

// Given some element of the look-and-say sequence, generate the next one.

function lookAndSaySequenceNextElement(str) {
  return str.match(/(.)\1*/g)
            .map(x=>x.length + x[0])
            .join('')
}

console.log(lookAndSaySequenceNextElement("13112221"))//"1113213211"
console.log(lookAndSaySequenceNextElement("1211"))//"111221"
console.log(lookAndSaySequenceNextElement("1"))//"11"