// Given a string s consisting only of letters 'a' and 'b'. In a single step you can remove one palindromic subsequence from s.

// Return the minimum number of steps to make the given string empty.

// A string is a subsequence of a given string, if it is generated by deleting some characters of a given string without changing its order.

// A string is called palindrome if is one that reads the same backward as well as forward.

const removePalindromeSub = (s) =>{
    if(s === '') return 0
    if(s === [...s].reverse().join('')) return 1
    return 2
}

console.log(removePalindromeSub("ababa"))//1
console.log(removePalindromeSub("abb"))//2
console.log(removePalindromeSub("baabb"))//2
console.log(removePalindromeSub(""))//0